"""
StutterSense — High-Resolution Transformer Pipeline
====================================================
Single-file script covering:
  • 39-dim MFCC trajectory  (MFCC + Δ + ΔΔ)  via librosa.feature.delta
  • Transformer Encoder (3 blocks, 4-head MHA, FFN, LayerNorm)
  • Learned positional encoding
  • Tensor-level data augmentation (Gaussian noise + time masking)
  • Focal Loss  (γ=2.0, α=0.25)  with higher focus on hard examples
  • StandardScaler persistence (frame-wise)
  • 128-frame sliding-window live inference
  • Gradient clipping (Adam + clipnorm=1.0)
  • ReduceLROnPlateau + early stopping (patience=10)
  • L2 regularization on all Dense layers
  • Classification report + Seaborn confusion-matrix heatmap
  • StandardScaler persistence (frame-wise)
  • 128-frame sliding-window live inference
  • Gradient clipping (Adam + clipnorm=1.0)
  • ReduceLROnPlateau + early stopping
  • Classification report + Seaborn confusion-matrix heatmap

Dataset : Pre-processed .npz tensors generated by build_wav_dataset.py
Classes : 0-NoStutter  1-Prolongation  2-Block  3-SoundRepetition  4-WordRepetition

Usage
-----
  python test_model.py --data_file ./sep28k_tensors.npz [--epochs 80]

Outputs written to ./stuttersense_output/:
  transformer_model.keras   – saved Keras model
  scaler.pkl                – fitted StandardScaler
  confusion_matrix.png      – heatmap
  classification_report.txt – per-class F1 report
  training_curves.png       – loss / accuracy curves
"""

import os
import sys
import argparse
import warnings
import pickle
import logging
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

# ── scikit-learn ──────────────────────────────────────────────────────────────
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# ── TensorFlow / Keras ────────────────────────────────────────────────────────
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model, callbacks

# ── librosa (feature extraction for live inference) ───────────────────────────
try:
    import librosa
    LIBROSA_AVAILABLE = True
except ImportError:
    LIBROSA_AVAILABLE = False

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(message)s",
                    datefmt="%H:%M:%S")
log = logging.getLogger("StutterSense")

# ═══════════════════════════════════════════════════════════════════════════════
# 0.  CONSTANTS
# ═══════════════════════════════════════════════════════════════════════════════
CLASS_NAMES  = ["NoStutter", "Prolongation", "Block", "SoundRepetition", "WordRepetition"]
N_CLASSES    = len(CLASS_NAMES)
N_MFCC       = 13          # base MFCCs
N_FEATURES   = 39          # 13 + 13Δ + 13ΔΔ  (training trajectory)
LIVE_FEATURES = 39         # matching the 39-dim Transformer input
SEQ_LEN      = 128         # time-steps per window (pad/truncate)
SR           = 16_000      # sample rate for live audio
WINDOW_SEC   = 3.0         # sliding window length
HOP_SEC      = 0.5         # sliding window hop

OUTPUT_DIR = Path("stuttersense_output")
OUTPUT_DIR.mkdir(exist_ok=True)

# ═══════════════════════════════════════════════════════════════════════════════
# 1.  FEATURE EXTRACTION — 39-dim MFCC trajectory
# ═══════════════════════════════════════════════════════════════════════════════

def compute_39dim_features(mfcc_matrix: np.ndarray) -> np.ndarray:
    """
    Given a (time, 13) MFCC matrix, append Δ and ΔΔ along the feature axis.
    Returns shape (time, 39).
    """
    delta     = librosa.feature.delta(mfcc_matrix.T, order=1).T   # (time, 13)
    delta2    = librosa.feature.delta(mfcc_matrix.T, order=2).T   # (time, 13)
    return np.concatenate([mfcc_matrix, delta, delta2], axis=-1)   # (time, 39)


def pad_or_truncate(arr: np.ndarray, seq_len: int = SEQ_LEN) -> np.ndarray:
    """Pad with zeros or truncate to a fixed sequence length."""
    t = arr.shape[0]
    if t >= seq_len:
        return arr[:seq_len]
    pad = np.zeros((seq_len - t, arr.shape[1]), dtype=arr.dtype)
    return np.concatenate([arr, pad], axis=0)


# ═══════════════════════════════════════════════════════════════════════════════
# 2.  DATA LOADING  (UPGRADED FOR PRE-PROCESSED .NPZ TENSORS)
# ═══════════════════════════════════════════════════════════════════════════════

def load_tensor_dataset(npz_path: str):
    """
    Loads the pre-processed (Samples, 128, 39) audio tensors directly.
    This replaces the old CSV method and ensures the model is trained 
    on actual temporal data, perfectly matching the live microphone input.
    """
    log.info(f"🚀 Loading High-Resolution Audio Tensors from {npz_path}...")
    
    if not os.path.exists(npz_path):
        raise FileNotFoundError(
            f"Dataset not found: {npz_path}.\n"
            "Please run 'python build_wav_dataset.py' first to generate this file from your .wav audio."
        )
        
    data = np.load(npz_path)
    X_seq = data['X']
    y_seq = data['y']
    
    log.info("Successfully Loaded Audio Tensors.")
    log.info("Sequence tensor shape for Transformer: %s", X_seq.shape) # Should be (N, 128, 39)
    log.info("Labels shape: %s", y_seq.shape)
    
    # Return a dummy label encoder to satisfy the main script's expected signature
    class DummyLE:
        def transform(self, x): return x
    
    return X_seq, y_seq, DummyLE()


# ═══════════════════════════════════════════════════════════════════════════════
# 3.  FOCAL LOSS
# ═══════════════════════════════════════════════════════════════════════════════

class FocalLoss(keras.losses.Loss):
    """
    Focal Loss for multi-class classification.
      FL(p_t) = -α_t · (1 − p_t)^γ · log(p_t)

    γ=1.5  — moderate focus on hard examples
    α=0.25 — mild down-weighting of the dominant NoStutter class
    """
    def __init__(self, gamma: float = 1.5, alpha: float = 0.25,
                 name: str = "focal_loss", **kwargs):
        # Pop 'reduction' and any other Keras-internal keys — do NOT forward them.
        # Different Keras versions use different Reduction enum values, so the
        # safest approach is to discard it and let Keras use its own default.
        kwargs.pop('reduction', None)
        super().__init__(name=name, **kwargs)
        self.gamma = gamma
        self.alpha = alpha

    def call(self, y_true, y_pred):
        y_true    = tf.cast(y_true, tf.int32)
        y_pred    = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)
        ce        = -tf.math.log(y_pred)                          # (B, C)
        one_hot   = tf.one_hot(y_true, depth=N_CLASSES)           # (B, C)
        p_t       = tf.reduce_sum(y_pred * one_hot, axis=-1)      # (B,)
        focal_w   = self.alpha * tf.pow(1.0 - p_t, self.gamma)    # (B,)
        loss      = focal_w * tf.reduce_sum(ce * one_hot, axis=-1)
        return tf.reduce_mean(loss)

    def get_config(self):
        base = super().get_config()
        base.update({"gamma": self.gamma, "alpha": self.alpha})
        return base


# ═══════════════════════════════════════════════════════════════════════════════
# 4.  TRANSFORMER ENCODER BLOCK
# ═══════════════════════════════════════════════════════════════════════════════

def transformer_encoder_block(x, d_model: int, num_heads: int,
                               ff_dim: int, dropout: float = 0.1):
    """
    One Transformer Encoder block:
      Multi-Head Self-Attention → Add & Norm → FFN → Add & Norm
    """
    # ── Multi-Head Self-Attention ─────────────────────────────────────────────
    attn_out = layers.MultiHeadAttention(
        num_heads=num_heads, key_dim=d_model // num_heads,
        dropout=dropout, name=None)(x, x)
    x = layers.LayerNormalization(epsilon=1e-6)(x + attn_out)

    # ── Feed-Forward Network ──────────────────────────────────────────────────
    ffn_out = layers.Dense(ff_dim, activation="relu")(x)
    ffn_out = layers.Dropout(dropout)(ffn_out)
    ffn_out = layers.Dense(d_model)(ffn_out)
    x = layers.LayerNormalization(epsilon=1e-6)(x + ffn_out)

    return x


def build_transformer_model(seq_len: int, n_features: int,
                             n_classes: int,
                             d_model: int = 256,
                             num_heads: int = 4,
                             ff_dim: int = 512,
                             num_blocks: int = 3,
                             dropout: float = 0.2,
                             l2_reg: float = 1e-4) -> Model:
    """
    Upgraded Transformer Encoder model for stuttering classification.

    Architecture (accuracy-optimised)
    ───────────────────────────────────
      Input projection  → d_model=256
      Learned positional encoding
      3 × Transformer Encoder Blocks (4-head MHA + FFN + LayerNorm)
      Global Average Pooling
      Dense(256, gelu) + Dropout(0.3)
      Dense(128, relu) + Dropout(0.2)
      Dense(n_classes, softmax)
    """
    inp = keras.Input(shape=(seq_len, n_features), name="mfcc_input")

    # ── linear projection to d_model ──────────────────────────────────────
    x = layers.Dense(d_model, name="input_projection")(inp)

    # ── learned positional encoding ──────────────────────────────────────
    positions = tf.range(start=0, limit=seq_len, delta=1)
    pos_emb   = layers.Embedding(input_dim=seq_len, output_dim=d_model,
                                  name="pos_embedding")(positions)
    x = x + pos_emb
    x = layers.Dropout(dropout)(x)

    # ── 3 Transformer Encoder Blocks ────────────────────────────────────
    for i in range(num_blocks):
        x = transformer_encoder_block(x, d_model=d_model,
                                      num_heads=num_heads,
                                      ff_dim=ff_dim,
                                      dropout=dropout)

    # ── Global Average Pooling ───────────────────────────────────────────
    x = layers.GlobalAveragePooling1D(name="global_avg_pool")(x)

    # ── Deeper classification head for improved minority class recall ───────
    x = layers.Dense(256, activation="gelu", name="clf_dense_1")(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(128, activation="relu", name="clf_dense_2")(x)
    x = layers.Dropout(0.2)(x)
    out = layers.Dense(n_classes, activation="softmax", name="predictions")(x)

    return Model(inputs=inp, outputs=out, name="StutterSense_Transformer_v2")


# ═══════════════════════════════════════════════════════════════════════════════
# 5.  SMOTE HELPER  (operates on flattened sequences)
# ═══════════════════════════════════════════════════════════════════════════════

def apply_smote(X: np.ndarray, y: np.ndarray) -> tuple:
    """
    Flatten (N, T, F) → (N, T*F), apply SMOTE, reshape back to (N', T, F).
    NOTE: Disabled by default — SMOTE on temporal data destroys the frame
    ordering that the Transformer depends on.  Use augment_minority() instead.
    """
    original_shape = X.shape[1:]            # (T, F)
    N, T, F = X.shape
    X_flat = X.reshape(N, T * F)

    class_counts = np.bincount(y)
    log.info("Class distribution before SMOTE: %s", dict(zip(range(N_CLASSES), class_counts)))

    smote = SMOTE(random_state=42, k_neighbors=min(5, np.min(class_counts) - 1))
    X_res, y_res = smote.fit_resample(X_flat, y)

    class_counts_after = np.bincount(y_res)
    log.info("Class distribution after  SMOTE: %s", dict(zip(range(N_CLASSES), class_counts_after)))

    return X_res.reshape(-1, T, F), y_res


def augment_minority(X: np.ndarray, y: np.ndarray,
                     target_ratio: float = 0.6,
                     noise_std: float = 0.05,
                     time_mask_max: int = 15) -> tuple:
    """
    Augment minority stutter classes with realistic tensor-level perturbations:
      • Gaussian noise injection  (simulates microphone variance)
      • Random time-frame masking (simulates dropout / codec loss)

    Minority classes are up-sampled until they reach `target_ratio` of the
    majority class count.  This preserves temporal structure completely.
    """
    counts       = np.bincount(y, minlength=N_CLASSES)
    majority_n   = int(counts.max())
    target_n     = int(majority_n * target_ratio)

    log.info("Class counts before augmentation: %s", dict(zip(CLASS_NAMES, counts)))

    X_aug_list = [X]
    y_aug_list = [y]

    rng = np.random.RandomState(42)

    for cls_idx in range(N_CLASSES):
        cls_mask = (y == cls_idx)
        cls_count = int(cls_mask.sum())
        if cls_count >= target_n:
            continue   # already enough samples — no augmentation needed

        X_cls = X[cls_mask]           # (C, 128, 39)
        needed = target_n - cls_count
        log.info("  Augmenting class %s: +%d samples", CLASS_NAMES[cls_idx], needed)

        aug_indices = rng.randint(0, cls_count, size=needed)
        X_src       = X_cls[aug_indices].copy()   # (needed, 128, 39)

        # 1. Gaussian noise
        noise = rng.normal(0, noise_std, X_src.shape).astype(np.float32)
        X_src = X_src + noise

        # 2. Random time masking — zero out up to time_mask_max consecutive frames
        for sample in X_src:
            mask_len   = rng.randint(1, time_mask_max + 1)
            mask_start = rng.randint(0, max(1, SEQ_LEN - mask_len))
            sample[mask_start: mask_start + mask_len, :] = 0.0

        X_aug_list.append(X_src)
        y_aug_list.append(np.full(needed, cls_idx, dtype=y.dtype))

    X_out = np.concatenate(X_aug_list, axis=0)
    y_out = np.concatenate(y_aug_list, axis=0)

    # Shuffle so augmented samples are interspersed with real ones
    perm  = rng.permutation(len(X_out))
    X_out, y_out = X_out[perm], y_out[perm]

    counts_after = np.bincount(y_out, minlength=N_CLASSES)
    log.info("Class counts after  augmentation: %s", dict(zip(CLASS_NAMES, counts_after)))
    return X_out, y_out


# ═══════════════════════════════════════════════════════════════════════════════
# 6.  SCALER FIT / PERSIST
# ═══════════════════════════════════════════════════════════════════════════════

def fit_and_save_scaler(X_train: np.ndarray, scaler_path: Path) -> StandardScaler:
    """
    Fit a StandardScaler on the training set (frame-wise across all time steps)
    and persist it for live inference.
    """
    N, T, F = X_train.shape
    X_flat = X_train.reshape(-1, F)
    scaler = StandardScaler()
    scaler.fit(X_flat)
    with open(scaler_path, "wb") as f:
        pickle.dump(scaler, f)
    log.info("Scaler saved → %s", scaler_path)
    return scaler


def apply_scaler(X: np.ndarray, scaler: StandardScaler) -> np.ndarray:
    N, T, F = X.shape
    return scaler.transform(X.reshape(-1, F)).reshape(N, T, F).astype(np.float32)


# ═══════════════════════════════════════════════════════════════════════════════
# 7.  EVALUATION HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def plot_confusion_matrix(y_true, y_pred, save_path: Path):
    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
                linewidths=0.5, ax=ax)
    ax.set_title("StutterSense — Confusion Matrix", fontsize=14, pad=12)
    ax.set_xlabel("Predicted Label", fontsize=11)
    ax.set_ylabel("True Label",      fontsize=11)
    plt.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)
    log.info("Confusion matrix saved → %s", save_path)


def save_classification_report(y_true, y_pred, save_path: Path):
    report = classification_report(y_true, y_pred,
                                   target_names=CLASS_NAMES,
                                   digits=4)
    log.info("\n%s", report)
    with open(save_path, "w") as f:
        f.write("StutterSense — Classification Report\n")
        f.write("=" * 50 + "\n")
        f.write(report)
    log.info("Classification report saved → %s", save_path)


# ═══════════════════════════════════════════════════════════════════════════════
# 8.  LIVE AUDIO INFERENCE  (COMPLETED: 39-dim sliding window)
# ═══════════════════════════════════════════════════════════════════════════════

def extract_live_features(audio: np.ndarray, sr: int = SR,
                           n_mfcc: int = N_MFCC) -> np.ndarray:
    """
    Extract 39-dim feature vector from a raw audio waveform array:
      13 MFCCs + 13 Deltas + 13 Delta-Deltas
    
    This completes the pipeline so live inference perfectly matches 
    the 39-dimensional Transformer training logic.
    """
    if not LIBROSA_AVAILABLE:
        raise RuntimeError("librosa is required for live inference.  pip install librosa")
    
    hop_length = 512
    
    # 1. Base 13 MFCCs
    mfcc_base = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=n_mfcc, hop_length=hop_length).T  # (T, 13)
    
    # 2. Compute Deltas & Delta-Deltas to match training trajectory
    delta  = librosa.feature.delta(mfcc_base.T, order=1).T    # (T, 13)
    delta2 = librosa.feature.delta(mfcc_base.T, order=2).T    # (T, 13)
    
    # 3. Combine into the final 39 features expected by the Transformer
    feats = np.concatenate([mfcc_base, delta, delta2], axis=-1)  # (T, 39)
    
    return feats


class LiveInferenceEngine:
    """
    Loads a trained StutterSense model + scaler and classifies 3-second
    sliding windows of live audio.

    For live use the model must accept (batch, SEQ_LEN, LIVE_FEATURES).
    """

    def __init__(self, model_path: str, scaler_path: str):
        self.model  = keras.models.load_model(model_path,
                                              custom_objects={"FocalLoss": FocalLoss})
        with open(scaler_path, "rb") as f:
            self.scaler = pickle.load(f)
        log.info("LiveInferenceEngine ready.")

    def predict_window(self, audio: np.ndarray,
                       sr: int = SR) -> tuple:
        """Return (predicted_class_name, confidence, probabilities_array)."""
        feats  = extract_live_features(audio, sr=sr)
        feats  = pad_or_truncate(feats)                              # (SEQ_LEN, 39)
        # scale
        F = feats.shape[-1]
        feats  = self.scaler.transform(feats.reshape(-1, F)).reshape(1, SEQ_LEN, F)
        probs  = self.model.predict(feats, verbose=0)[0]
        idx    = int(np.argmax(probs))
        return CLASS_NAMES[idx], float(probs[idx]), probs

    def run_sliding_window(self, audio: np.ndarray,
                           sr: int = SR,
                           window_sec: float = WINDOW_SEC,
                           hop_sec:    float = HOP_SEC) -> list:
        """
        Slide a 3-second window over a longer recording.
        Returns a list of dicts: {start_sec, end_sec, label, confidence}.
        """
        win_samples = int(window_sec * sr)
        hop_samples = int(hop_sec    * sr)
        results = []
        for start in range(0, len(audio) - win_samples + 1, hop_samples):
            window = audio[start: start + win_samples]
            label, conf, _ = self.predict_window(window, sr=sr)
            results.append({
                "start_sec":  round(start / sr, 2),
                "end_sec":    round((start + win_samples) / sr, 2),
                "label":      label,
                "confidence": round(conf, 4),
            })
        return results


# ═══════════════════════════════════════════════════════════════════════════════
# 9.  MAIN TRAINING PIPELINE
# ═══════════════════════════════════════════════════════════════════════════════

def train(args):
    # ── 9.1  Load data ────────────────────────────────────────────────────────
    X, y, label_encoder = load_tensor_dataset(args.data_file)

    # ── 9.2  Train / val / test split (70 / 15 / 15) ─────────────────────────
    X_tv, X_test, y_tv, y_test = train_test_split(
        X, y, test_size=0.15, random_state=42, stratify=y)
    X_train, X_val, y_train, y_val = train_test_split(
        X_tv, y_tv, test_size=0.1765, random_state=42, stratify=y_tv)
    # 0.1765 of 0.85 ≈ 15 % of total

    log.info("Split sizes — train: %d  val: %d  test: %d",
             len(X_train), len(X_val), len(X_test))

    # ── 9.3  StandardScaler (fit on training set only) ────────────────────────
    scaler_path = OUTPUT_DIR / "scaler.pkl"
    scaler      = fit_and_save_scaler(X_train, scaler_path)
    X_train     = apply_scaler(X_train, scaler)
    X_val       = apply_scaler(X_val,   scaler)
    X_test      = apply_scaler(X_test,  scaler)

    # ── 9.4  Augment minority classes (tensor-level, preserves temporal structure)
    if args.augment:
        X_train, y_train = augment_minority(
            X_train, y_train,
            target_ratio=0.65,
            noise_std=0.04,
            time_mask_max=12,
        )
    elif args.smote:
        try:
            X_train, y_train = apply_smote(X_train, y_train)
        except Exception as exc:
            log.warning("SMOTE failed (%s) — proceeding without resampling.", exc)

    # ── 9.5  Build model ──────────────────────────────────────────────────────
    n_features = X_train.shape[-1]          # 39 
    seq_len    = X_train.shape[1]           # 128

    model = build_transformer_model(
        seq_len    = seq_len,
        n_features = n_features,
        n_classes  = N_CLASSES,
        d_model    = args.d_model,
        num_heads  = 4,
        ff_dim     = args.ff_dim,
        num_blocks = 3,
        dropout    = args.dropout,
    )
    model.summary(print_fn=log.info)

    # ── 9.6  Compile with Focal Loss + gradient clipping ──────────────────
    model.compile(
        optimizer = keras.optimizers.Adam(
            learning_rate=args.lr,
            clipnorm=1.0),
        loss      = FocalLoss(gamma=2.0, alpha=0.25),   # gamma=2 focuses harder on minorities
        metrics   = ["accuracy"],
    )

    # ── 9.7  Callbacks ────────────────────────────────────────────────────────
    cb_list = [
        callbacks.EarlyStopping(monitor="val_accuracy", patience=10,
                                 restore_best_weights=True,
                                 mode="max", verbose=1),
        callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                                    patience=4, min_lr=1e-7, verbose=1),
        callbacks.ModelCheckpoint(filepath=str(OUTPUT_DIR / "transformer_model.keras"),
                                   monitor="val_accuracy", save_best_only=True,
                                   mode="max", verbose=0),
    ]

    # ── 9.8  Class weights — stronger penalty on minorities ─────────────────
    counts    = np.bincount(y_train, minlength=N_CLASSES).astype(float)
    majority  = counts.max()
    # Square-root smoothing: less aggressive than inverse, avoids exploding weights
    class_wts = {i: np.sqrt(majority / max(c, 1)) for i, c in enumerate(counts)}
    log.info("Class weights: %s",
             {CLASS_NAMES[i]: f"{w:.2f}" for i, w in class_wts.items()})

    # ── 9.9  Train ────────────────────────────────────────────────────────────
    history = model.fit(
        X_train, y_train,
        validation_data = (X_val, y_val),
        epochs          = args.epochs,
        batch_size      = args.batch,
        class_weight    = class_wts,
        callbacks       = cb_list,
        verbose         = 1,
    )

    # ── 9.10  Evaluate ────────────────────────────────────────────────────────
    log.info("── Test-set evaluation ──────────────────────────────")
    y_prob  = model.predict(X_test, verbose=0)
    y_pred  = np.argmax(y_prob, axis=-1)

    save_classification_report(y_test, y_pred,
                                OUTPUT_DIR / "classification_report.txt")
    plot_confusion_matrix(y_test, y_pred,
                          OUTPUT_DIR / "confusion_matrix.png")

    # ── 9.11  Training curve ──────────────────────────────────────────────────
    _plot_training_curves(history, OUTPUT_DIR / "training_curves.png")

    log.info("All artefacts saved to  %s/", OUTPUT_DIR)
    return model, scaler


def _plot_training_curves(history, save_path: Path):
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    for ax, metric, title in zip(axes,
                                  ["loss", "accuracy"],
                                  ["Focal Loss", "Accuracy"]):
        ax.plot(history.history[metric],          label="train")
        ax.plot(history.history[f"val_{metric}"], label="val")
        ax.set_title(title)
        ax.set_xlabel("Epoch")
        ax.legend()
    plt.tight_layout()
    fig.savefig(save_path, dpi=120)
    plt.close(fig)
    log.info("Training curves saved → %s", save_path)


# ═══════════════════════════════════════════════════════════════════════════════
# 10. CLI
# ═══════════════════════════════════════════════════════════════════════════════

def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="StutterSense — Transformer Training Pipeline",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    # paths
    p.add_argument("--data_file", default="./sep28k_tensors.npz",
                   help="Path to the .npz file from build_wav_dataset.py")
    # training hyper-params
    p.add_argument("--epochs",    type=int,   default=80,
                   help="Max epochs (early stopping usually triggers earlier)")
    p.add_argument("--batch",     type=int,   default=32)
    p.add_argument("--lr",        type=float, default=1e-4)
    p.add_argument("--dropout",   type=float, default=0.2)
    p.add_argument("--d_model",   type=int,   default=256,
                   help="Transformer embedding dimension")
    p.add_argument("--ff_dim",    type=int,   default=512,
                   help="Feed-forward inner dimension")
    # flags
    p.add_argument("--augment",    action="store_true", default=True,
                   help="Augment minority classes with noise+time-masking (recommended)")
    p.add_argument("--no_augment", dest="augment", action="store_false")
    p.add_argument("--smote",      action="store_true", default=False,
                   help="Apply SMOTE (not recommended for temporal data — use --augment)")
    p.add_argument("--no_smote",   dest="smote", action="store_false")
    # inference demo
    p.add_argument("--infer",     metavar="AUDIO_FILE",
                   help="Run live inference on an audio file (requires librosa)")
    return p.parse_args(argv)


# ═══════════════════════════════════════════════════════════════════════════════
# 11. ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    args = parse_args()

    # ── inference-only mode ───────────────────────────────────────────────────
    if args.infer:
        if not LIBROSA_AVAILABLE:
            sys.exit("librosa is required for live inference.  pip install librosa")
        model_path  = str(OUTPUT_DIR / "transformer_model.keras")
        scaler_path = str(OUTPUT_DIR / "scaler.pkl")
        if not os.path.exists(model_path):
            sys.exit(f"Trained model not found at {model_path}. "
                     "Run training first (without --infer).")
        engine = LiveInferenceEngine(model_path, scaler_path)
        audio, sr = librosa.load(args.infer, sr=SR, mono=True)
        log.info("Loaded audio: %.1f s  @  %d Hz", len(audio) / sr, sr)
        results = engine.run_sliding_window(audio, sr=sr)
        print("\n{:<10} {:<8} {:<18} {}".format(
            "Start(s)", "End(s)", "Label", "Confidence"))
        print("-" * 52)
        for r in results:
            print(f"{r['start_sec']:<10.2f} {r['end_sec']:<8.2f} "
                  f"{r['label']:<18} {r['confidence']:.4f}")
    else:
        # ── training mode ─────────────────────────────────────────────────────
        train(args)